language: node_js
node_js:
  - node
  - 8
git:
  depth: 3
after_success:
  - npm run coverage
  - npm run build
script:
  - npm run test
deploy:
  provider: npm
  email: i@charugin.ru
  api_key:
    secure: UnYeqdlxuA41RhikD5VxC92NFPpjgbN9fBEMHNNNJrlYo/u9ZzgMvZED3YR5HPNquTQeCRDtv0nOeDky4Bc5oktuu+OkqGgwbFSvSDcy+aZzfsEzl276w89zPjG0FodXNuqYDuDq7erM/nLGjKtBXmLhqV4+KOcY4CxLUKNnainsfNivchhu8SfL9P2tJ7JwssVvA6WfPnfUgSS+BtC0ZFZ7qBQljQp/yeggU2ZGwS/qJCM5o8lfwAFNd2XTee6Rito/6zwOqrr5FDQ7IBqfeMrtNGgWl3sLv6oJtxzkNAGIhh79QVloKfSlcIePe0pxte4oeDBoBeKHKDzvB4dgKgJuL4HOJQbtQ5fFuywjVkRtd0RvFoA/XY/d30y1iNWJN8ydTKkmxf+zvxa1/fQJwuqnGbQ3LetUjAULuba4AJ4bMWV7cypsqiMVvgUIx2tTd/jCBpoDnuPpPgMleeHcubbFjpW4x8FOUpEOW2oTkl3WNxUg/LLIrbXvnAQz+XqTXu2f5fYw6RZkRMdsnXUIixibVxr6x+rcNBY7BzTIOIegBGDp3qa2AeBk0VxozPU4QCmO842GYvZLzWellf5GaoAjh1gHNhYNecvX0PVfCVFjc8izRmKnoGQ06z4Nh0R0Ge8IhzE7xYa3WiDZLF73RdgrzU7CfwUf1alu8aijQtc=
  on:
    tags: true
    repo: RomiC/rsql-builder
  skip_cleanup: true
