language: node_js
node_js:
- node
- 8
git:
  depth: 3
after_success:
- npm run coverage
- npm run build
script:
- npm run test
deploy:
  provider: npm
  email: i@charugin.ru
  api_key:
    secure: P+6gr4NWQG2YcNV5XYq9aUFKMICmYMi51+1pNvJOzHuKbij/tIn874N2ETLO/XFJe5NxCzWRgJrShBdf+1mllYX5XqHepmD5GdtcWMz3+tN0BFLOIDSxZfhdMHvrmw1XLjcVyKvkO9uT/X/mXWPVJ8jMA8jQ5IHBCHGeU0LlUqONQMqtUQrUzXGeXdy/a2BgglpmqlCqnBDfBNqJx0dlUNFBns0f4HpON0fc0Jxz5bL9zy4gRF1AwP4wfS0FXnywBUUHKEvscQvhbcy1Cs7Ho8zUfhd44Zr+vTLbFqz64EaShP7ZR0y7FBPSF5Qek00O8LQyHNrR1cLE9JXNE8jxewXFVHPcznujUUJUsVbmH80iV4x4ZdZy6A7jPQyMcVKe72hZGYXUETpOZMVRDZU4cjDdvrVuQQb7dPm7W5Q3KR8ECmxn/x87hH5aGLjgQgePyzKKGhTdUj3wOhmxNhC98Xg4UpSYIRWAbE+TxwKgrpqZA4Rp60tasjpHbf/so8nHFEMW2kyPufTYvlpdPsLMu8RjPigWkXXIVA2NCck2Bg2Ml20GpLVgniBEeatwxVgvHAACpapCvNIakxeBjPSTmpMvPJfeJMdhR7SHdI1inpVO4dj8lj+F44ZlWsDG5JD2yLFmnUhilJuvJpKUOPpDUyYQnz/KkW7/qldTp0pwQ1s=
  on:
    tags: true
    repo: RomiC/rsql-builder
  skip_cleanup: true
