language: node_js
node_js:
  - 11.10
  - 10
  - 8
git:
  depth: 3
after_success:
  - npm run coverage
  - npm run build
script:
  - npm run test
deploy:
  provider: npm
  email: i@charugin.ru
  api_key:
    secure: "09qTqSi8r1piQzogoDAoDvAPlwr7hMbb+MkT5HzsfNGTQc1qH2y2Xmvuaub1QGmqRermAYESCcScVHPhcE0rn4s70Wp8xDHis9B3s2W42g1CDbH6L9YkIW3cCIyu0V/gPiGXiOFP7f02LPSphqnougiUrVtetlKlQBbaXhK+YdGP7z/dbXJYgtz1GsBDfncimd5Vk34oO+5d+3Ee42aGDLyVNZMd5N8GKup3YK+Unv2s/d/c08YFnHA67rH+fRiW1YQH1cUa8qxksDs0yxvsUsgJkycgYSiJ1zxUNR+FcgQgj2gytEHd/+tcNIe9uLIfnkbiynbBjuN+3LEgo9vek3AY3wjhSCAYuMwv1T2kEXTSNoIzC9Xp3H0TcBpeOLfi4qaNI7tIUCQ4K9ZtPEaJ8KbfS2Con4fsc01XdKXaV0MCW+jJgfG4kLuhfaHWIRu9TMdwfH+HvmXg9L8vvCpS6MXpy3d+zG9kV8EsCvAVDyZ4aTw48Uopal+TYzIbqgtImt+qHNpo5unB7lF05/4jC5arXwSEgOSEowhmLSZ/dk1fHMgLCclCLW+2UjDNfVi2q4gTY5NBKW6UnJ7/hGLWQNXl4GpGW1vHhbEBB/M1Oium/Pt+vqID49ZCl043j4tec1bPfkmORymGbgekcSdQcqSs7SWTG2XpH8J1R8TGZcM="
  on:
    tags: true
    repo: RomiC/rsql-builder
  skip_cleanup: true
